NAME	= unitTest

CPP_SRC := \
			src/main.cpp \
			src/tests/testObject.cpp \
			src/tests/performance/malloc-performance.cpp \
			src/tests/performance/ram-performance.cpp \
			src/tests/performance/rtos-performance.cpp \
			src/tests/performance/tcp-performance.cpp \
			src/tests/performance/udp-performance.cpp \
			src/tests/io/stdio-test.cpp \
			src/tests/io/nbio-test.cpp \
			src/tests/nbrtos/nbrtosTests.cpp \
			src/tests/nbrtos/nbrtosTaskCreate.cpp \
			src/tests/nbrtos/nbrtosLock.cpp \
			src/tests/nbrtos/nbrtosSem.cpp \
			src/tests/nbrtos/nbrtosMBox.cpp \
			src/tests/nbrtos/nbrtosQue.cpp \
			src/tests/nbrtos/nbrtosFifo.cpp \
			src/tests/nbrtos/nbrtosCrit.cpp \
			src/tests/nbrtos/nbrtosFlags.cpp \
			src/tests/nbrtos/nbrtosTimeTick.cpp \
			src/CppUTest/CommandLineArguments.cpp \
			src/CppUTest/CommandLineTestRunner.cpp \
			src/CppUTest/JUnitTestOutput.cpp \
			src/CppUTest/MemoryLeakDetector.cpp \
			src/CppUTest/MemoryLeakWarningPlugin.cpp \
			src/CppUTest/SimpleMutex.cpp \
			src/CppUTest/SimpleString.cpp \
			src/CppUTest/TeamCityTestOutput.cpp \
			src/CppUTest/TestFailure.cpp \
			src/CppUTest/TestFilter.cpp \
			src/CppUTest/TestHarness_c.cpp \
			src/CppUTest/TestMemoryAllocator.cpp \
			src/CppUTest/TestOutput.cpp \
			src/CppUTest/TestPlugin.cpp \
			src/CppUTest/TestRegistry.cpp \
			src/CppUTest/TestResult.cpp \
			src/CppUTest/TestTestingFixture.cpp \
			src/CppUTest/Utest.cpp \
			src/CppUTest/UtestPlatform.cpp \
			src/CppUTestExt/CodeMemoryReportFormatter.cpp \
			src/CppUTestExt/IEEE754ExceptionsPlugin.cpp \
			src/CppUTestExt/MemoryReportAllocator.cpp \
			src/CppUTestExt/MemoryReporterPlugin.cpp \
			src/CppUTestExt/MemoryReportFormatter.cpp \
			src/CppUTestExt/MockActualCall.cpp \
			src/CppUTestExt/MockExpectedCall.cpp \
			src/CppUTestExt/MockExpectedCallsList.cpp \
			src/CppUTestExt/MockFailure.cpp \
			src/CppUTestExt/MockNamedValue.cpp \
			src/CppUTestExt/MockSupport.cpp \
			src/CppUTestExt/MockSupport_c.cpp \
			src/CppUTestExt/MockSupportPlugin.cpp \
			src/CppUTestExt/OrderedTest.cpp
			
EXTRACXXFLAGS += -I"src"
DBEXTRACXXFLAGS += -I"src"

include $(NNDK_ROOT)/make/boilerplate.mk
